import type { CriteriaScores } from "@/lib/ms7";

/**
 * ДЕМО-НАБОР. Баллы сгенерированы для показа интерфейса и НЕ являются
 * результатом реального мониторинга перечисленных изданий. Тот же набор
 * лежит в supabase/schema.sql; после подключения Supabase данные
 * приходят из таблицы `media_rankings`.
 */
export interface RankingRow extends CriteriaScores {
  outlet_id: string;
  name: string;
  slug: string;
  ownership: "davlat" | "nodavlat";
  region: string;
  website: string;
}

export const DEMO_PERIOD = "Сайлов-2026, 1-босқич";

export const DEMO_RANKINGS: RankingRow[] = [
  {
    outlet_id: "kun-uz",
    name: "Kun.uz",
    slug: "kun-uz",
    website: "kun.uz",
    ownership: "nodavlat",
    region: "Тошкент",
    legal: 94,
    quality: 91,
    speed: 95,
    multimedia: 90,
    interactivity: 88,
    engagement: 96,
    convergence: 93,
  },
  {
    outlet_id: "gazeta-uz",
    name: "Gazeta.uz",
    slug: "gazeta-uz",
    website: "gazeta.uz",
    ownership: "nodavlat",
    region: "Тошкент",
    legal: 93,
    quality: 95,
    speed: 88,
    multimedia: 89,
    interactivity: 85,
    engagement: 90,
    convergence: 88,
  },
  {
    outlet_id: "daryo-uz",
    name: "Daryo.uz",
    slug: "daryo-uz",
    website: "daryo.uz",
    ownership: "nodavlat",
    region: "Тошкент",
    legal: 88,
    quality: 86,
    speed: 91,
    multimedia: 87,
    interactivity: 86,
    engagement: 92,
    convergence: 89,
  },
  {
    outlet_id: "uza",
    name: "UzA — Ўзбекистон МА",
    slug: "uza",
    website: "uza.uz",
    ownership: "davlat",
    region: "Тошкент",
    legal: 92,
    quality: 88,
    speed: 79,
    multimedia: 76,
    interactivity: 62,
    engagement: 71,
    convergence: 80,
  },
  {
    outlet_id: "qalampir-uz",
    name: "Qalampir.uz",
    slug: "qalampir-uz",
    website: "qalampir.uz",
    ownership: "nodavlat",
    region: "Тошкент",
    legal: 79,
    quality: 78,
    speed: 88,
    multimedia: 85,
    interactivity: 84,
    engagement: 89,
    convergence: 86,
  },
  {
    outlet_id: "xabar-uz",
    name: "Xabar.uz",
    slug: "xabar-uz",
    website: "xabar.uz",
    ownership: "davlat",
    region: "Тошкент",
    legal: 86,
    quality: 82,
    speed: 78,
    multimedia: 74,
    interactivity: 66,
    engagement: 70,
    convergence: 75,
  },
  {
    outlet_id: "repost-uz",
    name: "Repost.uz",
    slug: "repost-uz",
    website: "repost.uz",
    ownership: "nodavlat",
    region: "Тошкент",
    legal: 76,
    quality: 74,
    speed: 79,
    multimedia: 81,
    interactivity: 80,
    engagement: 78,
    convergence: 77,
  },
  {
    outlet_id: "podrobno-uz",
    name: "Podrobno.uz",
    slug: "podrobno-uz",
    website: "podrobno.uz",
    ownership: "nodavlat",
    region: "Тошкент",
    legal: 81,
    quality: 79,
    speed: 76,
    multimedia: 70,
    interactivity: 68,
    engagement: 72,
    convergence: 71,
  },
  {
    outlet_id: "yuz-uz",
    name: "Yuz.uz",
    slug: "yuz-uz",
    website: "yuz.uz",
    ownership: "davlat",
    region: "Тошкент",
    legal: 78,
    quality: 73,
    speed: 68,
    multimedia: 64,
    interactivity: 58,
    engagement: 61,
    convergence: 66,
  },
  {
    outlet_id: "anhor-uz",
    name: "Anhor.uz",
    slug: "anhor-uz",
    website: "anhor.uz",
    ownership: "nodavlat",
    region: "Тошкент",
    legal: 72,
    quality: 75,
    speed: 66,
    multimedia: 61,
    interactivity: 63,
    engagement: 59,
    convergence: 60,
  },
];
